### PR TITLE
chore: revise required Payload field for generic Event/Request, prevent missing field at entry passing

### PR DESCRIPTION
**Pull request by tanlethanh**

### CODE REVIEW

**Comment by tanlethanh** [comment]
My proposal from your change, 
- Event and Request are base of all Events, Requests with Any inline field to keep all the object field.
- We will not use Event/Request directly, whenever construct an event/request, we need to explicitly use correct Event/Request type for a specific event/request
- I use Any instead of Payload to prevent confusing. You might notice that some event has it own Data field, wrapped by Payload field as your previous impl.

**Comment by hnimtadd** [comment]
Did you check that Any field can capture remain fields of the event in the pushEvent handler

**Comment by tanlethanh** [comment]
Technically it should work by the way Go struct works :v Haven't test yet

**Comment by hnimtadd** [comment]
Unfortunately, the JSON unmarshaller cannot capture the Any field by default. By structuring the event this way, we have to either: 1. use 'any' as received event types for all lambda and service API handlers, or 2. unmarshal the event twice (capture the event type first, then unmarshal the event into a specific event).

**Comment by tanlethanh** [comment]
@hnimtadd how about forcing using Payload field, make thing consistent with a convention would make we less confusing for next step

**Pull request merged**
